// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCYu6IvhDydqemMdxtB3ByviDUONJUb87E',
    appId: '1:860394366020:web:c1ffa40b5e379840bf8811',
    messagingSenderId: '860394366020',
    projectId: 'fir-flutter-codelab-e0c70',
    authDomain: 'fir-flutter-codelab-e0c70.firebaseapp.com',
    storageBucket: 'fir-flutter-codelab-e0c70.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAir8CpGssfmC5FZdzoT8BV2Lfc2unyklY',
    appId: '1:860394366020:android:ddb9310453b410c3bf8811',
    messagingSenderId: '860394366020',
    projectId: 'fir-flutter-codelab-e0c70',
    storageBucket: 'fir-flutter-codelab-e0c70.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC8VfZtEgQWCjrxIXtE4hnFf52kHfCMSfc',
    appId: '1:860394366020:ios:e4314931dc609facbf8811',
    messagingSenderId: '860394366020',
    projectId: 'fir-flutter-codelab-e0c70',
    storageBucket: 'fir-flutter-codelab-e0c70.appspot.com',
    iosBundleId: 'com.example.gtkFlutter',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC8VfZtEgQWCjrxIXtE4hnFf52kHfCMSfc',
    appId: '1:860394366020:ios:e4314931dc609facbf8811',
    messagingSenderId: '860394366020',
    projectId: 'fir-flutter-codelab-e0c70',
    storageBucket: 'fir-flutter-codelab-e0c70.appspot.com',
    iosBundleId: 'com.example.gtkFlutter',
  );

}